#!/usr/bin/env julia
# ---------------------------------------------------------------------------
# Build docs/interactive/cubed_sphere.html — a self-contained D3 page that
# illustrates the GEOS-native cubed-sphere panels (drag-rotatable globe) and
# the halo-exchange connectivity (FV3 staircase net with hover-linked edges).
#
# The geometry is the REAL production mesh, not a sketch: corners come from
# `Grids.panel_cell_corner_lonlat` on a `GMAOCubedSphereDefinition` mesh (the
# GEOS file panel convention, GMAO equal-distance law, −10° lon shift) and the
# edge table is `Grids.default_panel_connectivity()` — the same table
# `panel_connectivity.jl` uses to rotate panel-edge fluxes at runtime.
#
# Usage:
#   julia --project=. scripts/diagnostics/build_cs_interactive.jl [Nc]
# Nc defaults to 16 (fine enough to show the equal-distance spacing, small
# enough to keep the HTML self-contained at ~100 kB).
# ---------------------------------------------------------------------------

using AtmosTransport
using AtmosTransport.Grids: CubedSphereMesh, GMAOCubedSphereDefinition,
    panel_cell_corner_lonlat, panel_cell_center_lonlat,
    default_panel_connectivity

Nc = isempty(ARGS) ? 16 : parse(Int, ARGS[1])
mesh = CubedSphereMesh(; Nc = Nc, definition = GMAOCubedSphereDefinition())
conn = default_panel_connectivity()

_wrap180(lon) = lon > 180 ? lon - 360 : lon
_fmt(x) = string(round(Float64(x); digits = 4))

# corners[i][j] = [lon, lat] in JSON; i = local X index, j = local Y index.
function _panel_corners_json(panel::Int)
    lons, lats = panel_cell_corner_lonlat(mesh, panel)
    rows = String[]
    for i in axes(lons, 1)
        push!(rows, "[" * join(("[$(_fmt(_wrap180(lons[i, j]))),$(_fmt(lats[i, j]))]"
                                for j in axes(lons, 2)), ",") * "]")
    end
    return "[" * join(rows, ",") * "]"
end

function _panel_center_json(panel::Int)
    lons, lats = panel_cell_center_lonlat(mesh, panel)
    c = (size(lons, 1) + 1) ÷ 2
    return "[$(_fmt(_wrap180(lons[c, c]))),$(_fmt(lats[c, c]))]"
end

panels_json = "[" * join(("{\"id\":$p,\"corners\":$(_panel_corners_json(p))}"
                          for p in 1:6), ",") * "]"
centers_json = "[" * join((_panel_center_json(p) for p in 1:6), ",") * "]"
conn_json = "[" * join(("[" * join(("{\"panel\":$(conn.neighbors[p][e].panel)," *
                                    "\"orient\":$(conn.neighbors[p][e].orientation)}"
                                    for e in 1:4), ",") * "]"
                        for p in 1:6), ",") * "]"

# Local-axis meaning per panel (the panels-4/5 quarter-turn gotcha).
notes = ["X→east, Y→north", "X→east, Y→north", "north polar cap",
         "X→south, Y→east (90° CW)", "X→south, Y→east (90° CW)",
         "south polar cap"]
notes_json = "[" * join(("\"$n\"" for n in notes), ",") * "]"

geometry = """{
  "Nc": $Nc,
  "convention": "GEOS native (GMAO equal-distance gnomonic, −10° lon shift)",
  "panels": $panels_json,
  "centers": $centers_json,
  "connectivity": $conn_json,
  "panel_notes": $notes_json
}"""

root = normpath(joinpath(@__DIR__, "..", ".."))
template = read(joinpath(root, "docs", "interactive", "cubed_sphere_template.html"), String)
occursin("__GEOMETRY_JSON__", template) ||
    error("template lacks the __GEOMETRY_JSON__ placeholder")
html = replace(template, "__GEOMETRY_JSON__" => geometry)
# strip the template-only warning comment
html = replace(html,
    r"<!-- TEMPLATE — do not open directly\..*?-->\n"s =>
    "<!-- GENERATED by scripts/diagnostics/build_cs_interactive.jl — edit the template, not this file. -->\n")

out = joinpath(root, "docs", "interactive", "cubed_sphere.html")
write(out, html)
println("wrote $(out) ($(round(filesize(out) / 1024; digits = 1)) kB, C$Nc geometry)")
